version: '2'

volumes:
  conpot_logs:
  cowrie_downloads:
  cowrie_keys:
  cowrie_logs:
  cowrie_tty:
  glastopf_db:
  glastopf_logs:
  mailoney_logs:
  rdpy_logs:
  spiderfoot_db:
  vnclowpot_logs:

services:
  logstash:
    build: logstash/
    ports:
      - 127.0.0.1:5044:5044
    depends_on:
      - elasticsearch
    restart: unless-stopped
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./listbot:/etc/listbot/
      - conpot_logs:/var/log/conpot
      - cowrie_logs:/var/log/cowrie
      - glastopf_logs:/var/log/glastopf
      - mailoney_logs:/var/log/mailoney
      - rdpy_logs:/var/log/rdpy
      - vnclowpot_logs:/var/log/vnclowpot
  conpot:
    image: dtagdevsec/conpot:1710
    ports:
     - 1025:1025
     - 50100:50100
    volumes:
      - conpot_logs:/var/log/conpot
  cowrie:
    image: dtagdevsec/cowrie:1710
    cap_add:
      - NET_BIND_SERVICE
    ports:
     - 22:2222
     - 23:2223
    volumes:
     - cowrie_downloads:/home/cowrie/cowrie/dl
     - cowrie_keys:/home/cowrie/cowrie/etc
     - cowrie_logs:/home/cowrie/cowrie/log
     - cowrie_tty:/home/cowrie/cowrie/log/tty
  glastopf:
    image: dtagdevsec/glastopf:1710
    ports:
     - 80:80
    volumes:
     - glastopf_db:/opt/glastopf/db
     - glastopf_logs:/opt/glastopf/log
  mailoney:
    image: dtagdevsec/mailoney:1710
    ports:
     - 25:2525
    volumes:
    - mailoney_logs:/opt/mailoney/logs
  rdpy:
    image: dtagdevsec/rdpy:1710
    ports:
     - 3389:3389
    volumes:
     - rdpy_logs:/var/log/rdpy
  # spiderfoot:
  #   image: dtagdevsec/spiderfoot:1710
  #   ports:
  #    - 127.0.0.1:64303:8080
  #   volumes:
  #    - spiderfoot_db:/home/spiderfoot/spiderfoot.db
  vnclowpot:
    image: dtagdevsec/vnclowpot:1710
    ports:
     - 5900:5900
    volumes:
     - vnclowpot_logs:/var/log/vnclowpot
