version: '2'

volumes:
  elasticsearch-data-volume:

services:
  elasticsearch:
    image: elasticsearch:5.2
    command: elasticsearch
    # environment:
    #    ES_JAVA_OPTS: "-Xms8g -Xmx8g"
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    restart: unless-stopped
  kibana:
    image: kibana:5.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: unless-stopped
